# -*- mode: python ; coding: utf-8 -*-
# SIMANIS62 Backend PyInstaller Spec File
# Generated by build_backend.ps1

import sys
from pathlib import Path

block_cipher = None

# Project paths
backend_path = Path('backend/app')

# Hidden imports untuk FastAPI + Uvicorn stack
# CRITICAL: Uvicorn memerlukan banyak hidden imports
hiddenimports = [
    # Uvicorn core
    'uvicorn',
    'uvicorn.main',
    'uvicorn.config',
    'uvicorn.server',
    'uvicorn.logging',
    'uvicorn.loops',
    'uvicorn.loops.auto',
    'uvicorn.loops.asyncio',
    'uvicorn.protocols',
    'uvicorn.protocols.http',
    'uvicorn.protocols.http.auto',
    'uvicorn.protocols.http.h11_impl',
    'uvicorn.protocols.http.httptools_impl',
    'uvicorn.protocols.websockets',
    'uvicorn.protocols.websockets.auto',
    'uvicorn.protocols.websockets.websockets_impl',
    'uvicorn.lifespan',
    'uvicorn.lifespan.on',
    'uvicorn.lifespan.off',
    
    # FastAPI & Starlette
    'fastapi',
    'fastapi.applications',
    'fastapi.routing',
    'fastapi.middleware',
    'fastapi.middleware.cors',
    'starlette',
    'starlette.routing',
    'starlette.middleware',
    'starlette.responses',
    'starlette.requests',
    
    # Pydantic
    'pydantic',
    'pydantic.fields',
    'pydantic_settings',
    'pydantic_core',
    
    # SQLModel & SQLAlchemy
    'sqlmodel',
    'sqlalchemy',
    'sqlalchemy.sql.default_comparator',
    'sqlalchemy.ext.asyncio',
    
    # Security
    'passlib',
    'passlib.context',
    'passlib.handlers',
    'passlib.handlers.bcrypt',
    'bcrypt',
    
    # Other dependencies
    'email_validator',
    'anyio',
    'anyio._backends',
    'anyio._backends._asyncio',
    'httptools',
    'websockets',
    'h11',
    'click',
    'typing_extensions',
    
    # App modules
    'app',
    'app.main',
    'app.api',
    'app.api.v1',
    'app.api.v1.router',
    'app.core',
    'app.core.config',
    'app.core.database',
    'app.core.security',
    'app.models',
    'app.schemas',
    'app.services',
    'app.repositories',
]

a = Analysis(
    ['backend/app/main.py'],
    pathex=['backend'],
    binaries=[],
    datas=[
        # Include any data files if needed
        # ('backend/app/templates', 'app/templates'),
    ],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'PIL',
        'cv2',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# IMPORTANT: Menggunakan onedir (bukan onefile) karena uvicorn issue
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,  # onedir mode
    name='Simanis62.API',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,  # Keep console for server logs
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='frontend/Simanis62.WPF/Resources/app.ico' if Path('frontend/Simanis62.WPF/Resources/app.ico').exists() else None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Simanis62.API',
)
