<#
.SYNOPSIS
    Build SIMANIS62 Backend dengan PyInstaller
    
.DESCRIPTION
    Script untuk mengompilasi backend FastAPI menjadi executable.
    PENTING: Menggunakan --onedir (bukan --onefile) karena uvicorn
    tidak kompatibel dengan mode onefile.
    
.PARAMETER OutputDir
    Direktori output untuk build. Default: dist
    
.PARAMETER Clean
    Bersihkan build sebelumnya sebelum build baru
    
.EXAMPLE
    .\build_backend.ps1
    
.EXAMPLE
    .\build_backend.ps1 -Clean
    
.NOTES
    Author: SIMANIS62 Team
    Version: 1.0
    Date: 2026-01-12
    
    REQUIREMENTS:
    - Python 3.12
    - PyInstaller: pip install pyinstaller
#>

param(
    [string]$OutputDir = "dist",
    [switch]$Clean
)

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir
$BackendDir = Join-Path $ProjectRoot "backend"
$VenvDir = Join-Path $BackendDir ".venv"
$DistDir = Join-Path $ProjectRoot $OutputDir

Write-Host "=========================================="
Write-Host "SIMANIS62 Backend Build"
Write-Host "=========================================="
Write-Host "Project Root: $ProjectRoot"
Write-Host "Backend Dir: $BackendDir"
Write-Host "Output Dir: $DistDir"

# Activate virtual environment
$VenvActivate = Join-Path $VenvDir "Scripts\Activate.ps1"
if (Test-Path $VenvActivate) {
    Write-Host "`nActivating virtual environment..."
    . $VenvActivate
} else {
    Write-Host "WARNING: Virtual environment not found at $VenvDir" -ForegroundColor Yellow
    Write-Host "Using system Python..."
}

# Check PyInstaller
Write-Host "`nChecking PyInstaller..."
$PyInstallerVersion = python -c "import PyInstaller; print(PyInstaller.__version__)" 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: PyInstaller not installed!" -ForegroundColor Red
    Write-Host "Please run: pip install pyinstaller"
    exit 1
}
Write-Host "PyInstaller version: $PyInstallerVersion"

# Clean previous build
if ($Clean) {
    Write-Host "`nCleaning previous build..."
    $BuildDir = Join-Path $ProjectRoot "build"
    if (Test-Path $BuildDir) { Remove-Item $BuildDir -Recurse -Force }
    
    $ApiDistDir = Join-Path $DistDir "Simanis62.API"
    if (Test-Path $ApiDistDir) { Remove-Item $ApiDistDir -Recurse -Force }
    
    $SpecFile = Join-Path $ProjectRoot "Simanis62.API.spec"
    if (Test-Path $SpecFile) { Remove-Item $SpecFile -Force }
}

# Create spec file content
Write-Host "`nCreating PyInstaller spec file..."
$SpecContent = @'
# -*- mode: python ; coding: utf-8 -*-
# SIMANIS62 Backend PyInstaller Spec File
# Generated by build_backend.ps1

import sys
from pathlib import Path

block_cipher = None

# Project paths
backend_path = Path('backend/app')

# Hidden imports untuk FastAPI + Uvicorn stack
# CRITICAL: Uvicorn memerlukan banyak hidden imports
hiddenimports = [
    # Uvicorn core
    'uvicorn',
    'uvicorn.main',
    'uvicorn.config',
    'uvicorn.server',
    'uvicorn.logging',
    'uvicorn.loops',
    'uvicorn.loops.auto',
    'uvicorn.loops.asyncio',
    'uvicorn.protocols',
    'uvicorn.protocols.http',
    'uvicorn.protocols.http.auto',
    'uvicorn.protocols.http.h11_impl',
    'uvicorn.protocols.http.httptools_impl',
    'uvicorn.protocols.websockets',
    'uvicorn.protocols.websockets.auto',
    'uvicorn.protocols.websockets.websockets_impl',
    'uvicorn.lifespan',
    'uvicorn.lifespan.on',
    'uvicorn.lifespan.off',
    
    # FastAPI & Starlette
    'fastapi',
    'fastapi.applications',
    'fastapi.routing',
    'fastapi.middleware',
    'fastapi.middleware.cors',
    'starlette',
    'starlette.routing',
    'starlette.middleware',
    'starlette.responses',
    'starlette.requests',
    
    # Pydantic
    'pydantic',
    'pydantic.fields',
    'pydantic_settings',
    'pydantic_core',
    
    # SQLModel & SQLAlchemy
    'sqlmodel',
    'sqlalchemy',
    'sqlalchemy.sql.default_comparator',
    'sqlalchemy.ext.asyncio',
    
    # Security
    'passlib',
    'passlib.context',
    'passlib.handlers',
    'passlib.handlers.bcrypt',
    'bcrypt',
    
    # Other dependencies
    'email_validator',
    'anyio',
    'anyio._backends',
    'anyio._backends._asyncio',
    'httptools',
    'websockets',
    'h11',
    'click',
    'typing_extensions',
    
    # App modules
    'app',
    'app.main',
    'app.api',
    'app.api.v1',
    'app.api.v1.router',
    'app.core',
    'app.core.config',
    'app.core.database',
    'app.core.security',
    'app.models',
    'app.schemas',
    'app.services',
    'app.repositories',
]

a = Analysis(
    ['backend/app/main.py'],
    pathex=['backend'],
    binaries=[],
    datas=[
        # Include any data files if needed
        # ('backend/app/templates', 'app/templates'),
    ],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'PIL',
        'cv2',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# IMPORTANT: Menggunakan onedir (bukan onefile) karena uvicorn issue
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,  # onedir mode
    name='Simanis62.API',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,  # Keep console for server logs
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='frontend/Simanis62.WPF/Resources/app.ico' if Path('frontend/Simanis62.WPF/Resources/app.ico').exists() else None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Simanis62.API',
)
'@

$SpecFile = Join-Path $ProjectRoot "Simanis62.API.spec"
Set-Content -Path $SpecFile -Value $SpecContent -Encoding UTF8
Write-Host "Spec file created: $SpecFile"

# Run PyInstaller
Write-Host "`nRunning PyInstaller..."
Write-Host "This may take several minutes..."

Push-Location $ProjectRoot
try {
    pyinstaller --clean --noconfirm $SpecFile
    
    if ($LASTEXITCODE -ne 0) {
        throw "PyInstaller failed with exit code $LASTEXITCODE"
    }
    
    Write-Host "`n=========================================="
    Write-Host "Build completed successfully!" -ForegroundColor Green
    Write-Host "=========================================="
    
    $OutputPath = Join-Path $DistDir "Simanis62.API"
    Write-Host "Output: $OutputPath"
    
    # List output files
    $Files = Get-ChildItem $OutputPath -Recurse | Measure-Object -Property Length -Sum
    Write-Host "Total files: $($Files.Count)"
    Write-Host "Total size: $([math]::Round($Files.Sum / 1MB, 2)) MB"
    
} finally {
    Pop-Location
}
